# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 08:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryPart', models.CharField(choices=[(b'Toyota', b'Toyota'), (b'Cross country', b'Cross country'), (b'Vox wagen', b'Vox wagen'), (b'Suzuki', b'Suzuki'), (b'Mahindra', b'Mahindra'), (b'Honda', b'Honda'), (b'Hyunda', b'Hyunda'), (b'Volvo', b'Volvo'), (b'Daihatsu', b'Daihatsu')], max_length=40)),
                ('categoryImage', models.ImageField(upload_to=b'category/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default=b'default.jpg', upload_to=b'profiles/')),
                ('country', models.TextField(max_length=100)),
                ('contact', models.IntegerField(default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePart', models.CharField(choices=[(b'Head lights', b'Head lights'), (b'Brake lights', b'Brake lights'), (b'Tail lights', b'Tail lights'), (b'Tail gate', b'Tail gate'), (b'Mirrors', b'Mirrors'), (b'Hoods', b'Hoods'), (b'Window', b'Window'), (b'Door', b'Door'), (b'Tire', b'Tire'), (b'Petrol tank', b'Petrol tank'), (b'Roof', b'Roof'), (b'Steering wheel', b'Steering wheel'), (b'Engine', b'Engine')], max_length=40)),
                ('price', models.IntegerField()),
                ('locationPart', models.CharField(choices=[(b'Gatsata', b'Gatsata'), (b'Nyamirambo', b'Nyamirambo'), (b'Remera', b'Remera'), (b'Nyabugogo', b'Nyabugogo')], max_length=40)),
                ('ImagePart', models.ImageField(upload_to=b'spareparts/')),
                ('Phone', models.IntegerField()),
                ('carCat', models.ManyToManyField(to='carapp.CarCategory')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='sparePart',
            field=models.ManyToManyField(blank=True, null=True, to='carapp.SpareParts'),
        ),
    ]
