# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-10 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryPart', models.CharField(choices=[(b'Toyota', b'Toyota'), (b'Cross country', b'Cross country'), (b'Vox wagen', b'Vox wagen'), (b'Suzuki', b'Suzuki'), (b'Mahindra', b'Mahindra'), (b'Honda', b'Honda'), (b'Hyunda', b'Hyunda'), (b'Volvo', b'Volvo'), (b'Daihatsu', b'Daihatsu')], max_length=40)),
                ('categoryImage', models.ImageField(upload_to=b'category/')),
            ],
        ),
        migrations.CreateModel(
            name='CarMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name=b'email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name=b'date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name=b'last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('actives', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('partner_image', models.ImageField(null=True, upload_to=b'partner/')),
                ('approved', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=60, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default=b'default.jpg', upload_to=b'profiles/')),
                ('country', models.TextField(max_length=100)),
                ('contact', models.IntegerField(default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePart', models.CharField(choices=[(b'Head lights', b'Head lights'), (b'Brake lights', b'Brake lights'), (b'Tail lights', b'Tail lights'), (b'Tail gate', b'Tail gate'), (b'Mirrors', b'Mirrors'), (b'Hoods', b'Hoods'), (b'Window', b'Window'), (b'Door', b'Door'), (b'Tyres', b'Tyres'), (b'Petrol tank', b'Petrol tank'), (b'Roof', b'Roof'), (b'Steering wheel', b'Steering wheel'), (b'Engine', b'Engine'), (b'wheel tyres', b'wheel tyres')], max_length=40)),
                ('price', models.IntegerField()),
                ('locationPart', models.CharField(choices=[(b'Gatsata', b'Gatsata'), (b'Nyamirambo', b'Nyamirambo'), (b'Remera', b'Remera'), (b'Nyabugogo', b'Nyabugogo')], max_length=40)),
                ('ImagePart', models.ImageField(upload_to=b'spareparts/')),
                ('Phone', models.IntegerField()),
                ('categoryPart', models.CharField(choices=[(b'Toyota', b'Toyota'), (b'Cross country', b'Cross country'), (b'Vox wagen', b'Vox wagen'), (b'Suzuki', b'Suzuki'), (b'Mahindra', b'Mahindra'), (b'Honda', b'Honda'), (b'Hyunda', b'Hyunda'), (b'Volvo', b'Volvo'), (b'Daihatsu', b'Daihatsu')], max_length=40)),
                ('categoryImage', models.ImageField(blank=True, upload_to=b'category/')),
                ('carCat', models.ManyToManyField(to='carapp.CarCategory')),
                ('partner_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.Partners')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='sparePart',
            field=models.ManyToManyField(blank=True, null=True, to='carapp.SpareParts'),
        ),
    ]
