# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='categoryImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'category/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spareparts',
            name='categoryPart',
            field=models.CharField(choices=[(b'Toyota', b'Toyota'), (b'Cross country', b'Cross country'), (b'Vox wagen', b'Vox wagen'), (b'Suzuki', b'Suzuki'), (b'Mahindra', b'Mahindra'), (b'Honda', b'Honda'), (b'Hyunda', b'Hyunda'), (b'Volvo', b'Volvo'), (b'Daihatsu', b'Daihatsu')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
