# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-21 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totals',
            new_name='total',
        ),
    ]
