# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-20 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='Phone',
            new_name='Phones',
        ),
    ]
