# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-05 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparts',
            name='carCat',
            field=models.ManyToManyField(to='carapp.CarCategory'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='categoryPart',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Cross country', 'Cross country'), ('Vox wagen', 'Vox wagen'), ('Suzuki', 'Suzuki'), ('Mahindra', 'Mahindra'), ('Honda', 'Honda'), ('Hyunda', 'Hyunda'), ('Volvo', 'Volvo'), ('Daihatsu', 'Daihatsu')], max_length=40),
        ),
    ]
