# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-30 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='CarCategory',
            field=models.ManyToManyField(blank=True, null=True, to='carapp.CarCategory'),
        ),
    ]
