# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='age',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
