# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-21 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_auto_20191121_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='active',
            new_name='actives',
        ),
    ]
