# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-21 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_auto_20191120_1000'),
        ('carapp', '0002_auto_20191118_1601'),
    ]

    operations = [
    ]
